name: Build and Publish Python Package

on:
  push:
    paths:
    # Trigger only if changes are in the app/ folder 
    - 'app/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install setuptools wheel twine

      - name: Build the package
        run: |
          python setup.py sdist bdist_wheel

      # Make sure that the version is updated in setup.py
      # TODO: Automate version bump if necessary
      - name: Publish to PyPI
        run: |
          twine upload dist/*  # Upload the built package to PyPI
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}